# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:
    

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Retrieve secret from Key Vault
      id: keyvault
      uses: azure/CLI@v1
      with:
        inlineScript: |
          SECRET_VALUE=$(az keyvault secret show --name test-secret --vault-name ${{ secrets.KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$SECRET_VALUE"
          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV
    - name: Use retrieved secret
      run: |
        echo "The secret is successfully retrieved!"
        echo $SECRET_VALUE | md5sum


    - uses: sbiryukov-demo-org/.github/.github/actions/build-node@main
      with:
        node-version: '11'
        cache: 'npm'
        directory: "./web"

    # create a package with the built code
    - name: Create package
      run: |
        echo "Creating package with built code..."
        mkdir -p package
        cp -r web/build/* package/
        echo "Package created successfully."

    - name: Zip package
      run: |
        echo "Zipping the package..."
        zip -r package.zip package/
        echo "Package zipped successfully."

    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: package.zip


