# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Retrieve secret from Key Vault
      id: keyvault
      uses: azure/CLI@v1
      with:
        inlineScript: |
          SECRET_VALUE=$(az keyvault secret show --name test-secret --vault-name ${{ secrets.KEYVAULT_NAME }} --query value -o tsv)
          echo "::add-mask::$SECRET_VALUE"
          echo "SECRET_VALUE=$SECRET_VALUE" >> $GITHUB_ENV
    - name: Use retrieved secret
      run: echo "The secret is successfully retrieved!"


    - uses: sbiryukov-demo-org/.github/.github/actions/build-node@main
      with:
        node-version: '11'
        cache: 'npm'
        directory: "./web"
